#!/bin/bash
set -euo pipefail

CFG="/config/prosody.cfg.lua"
USER="${JITSI_MODERATOR_USER:-teacher}"
DOM="${JITSI_DOMAIN:-meet.jitsi}"
PASS="${JITSI_MODERATOR_PASS:-letmein2020}"

echo "🔐 s6: ensuring moderator ${USER}@${DOM}"

# Wait until prosody config exists (generated by 10-config)
for i in {1..30}; do
  [ -f "$CFG" ] && break
  sleep 1
done
[ -f "$CFG" ] || { echo "❌ prosody.cfg.lua missing"; exit 0; }

# Delete (if exists) then register with desired password
prosodyctl --config "$CFG" deluser "${USER}@${DOM}" 2>/dev/null || true
prosodyctl --config "$CFG" register "$USER" "$DOM" "$PASS" || true

echo "✅ moderator ready: ${USER}@${DOM}"
